// packages/flatline-solid/src/components/input/input.tsx
import clsx from 'clsx/lite';
import { type JSX, splitProps } from 'solid-js';
import { inputClass } from './class';
import './input.css';

export type InputBaseProps = JSX.InputHTMLAttributes<HTMLInputElement>;

export interface InputProps extends InputBaseProps {}

export function Input(props: InputProps) {
	const [local, rest] = splitProps(props, ['class', 'children']);

	const rootClass = () => clsx(inputClass.root, local.class);

	return (
		<input
			class={rootClass()}
			{...rest}
		/>
	);
}

// packages/flatline/src/components/input/input.tsx
import './input.css';
import clsx from 'clsx/lite';
import { inputClass } from './classname';
import type { InputHTMLAttributes } from 'react';

export type InputProps = InputHTMLAttributes<HTMLInputElement>;

export function Input(props: InputProps) {
	const { className, ...rest } = props;
	const rootClass = clsx(inputClass.root, className);

	return (
		<input className={rootClass} {...rest} />
	)
}
