// packages/flatline-solid/src/components/button/button.tsx
import clsx from 'clsx/lite';
import { mergeProps, splitProps, type JSX } from 'solid-js';
import { buttonClass, type ButtonColor, type ButtonVariant } from './class';
import './button.css';

export type ButtonBaseProps = JSX.ButtonHTMLAttributes<HTMLButtonElement>;

export interface ButtonProps extends ButtonBaseProps {
	variant?: ButtonVariant;
	color?: ButtonColor;
}

export function Button(props: ButtonProps) {
	const merged = mergeProps(
		{
			type: 'button',
			variant: 'solid',
			color: 'primary',
		} as const,
		props,
	);
	const [local, rest] = splitProps(merged, ['class', 'children', 'variant', 'color']);

	const rootClass = () =>
		clsx(buttonClass.root, buttonClass.variant[local.variant], buttonClass.color[local.color], local.class);

	return (
		<button class={rootClass()} {...rest}>
			{local.children}
		</button>
	);
}

// packages/flatline/src/components/button/button.tsx
import clsx from 'clsx/lite';
import { buttonClass } from './classname';
import './button.css';

export type ButtonProps = React.HtmlHTMLAttributes<HTMLButtonElement>;

export function Button(props: ButtonProps) {
    const { className, children, ...rest } = props;
    const rootClass = clsx(buttonClass.root, className);

    return (
        <button className={rootClass} {...rest}>
            {children}
        </button>
    )
}
